### ISSUE TITLE
Potential confusion

### ISSUE THREAD

**Issue by Caketaco** [ErdbeerbaerLP/MMCMGA#1]
With the name of the mod being what it is, combined with how it removes a trans artist's work, the mod may be seen as transphobic.

**Comment by Kennybust** [comment]
Imagine being called transphobic because you don't like the work of the producer

**Comment by ErdbeerbaerLP** [comment]
Updated the modrinth description to clearly state that this mod is not meant to be transphobic. If you have some suggestions for improving that text, feel free to re-open this
